# Generated by Django 3.1.7 on 2021-04-03 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210401_0000'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehicleinfo',
            name='vehicle_inf_id_a1cfd9_idx',
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='vehicle_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_colors_id', to='api.vehiclecolor'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='vehicle_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_companyid', to='api.vehiclecompany'),
        ),
        migrations.AlterField(
            model_name='vehicleinfo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='vehicleinfo',
            index=models.Index(fields=['id', 'vehicle_model', 'user', 'vehicle_color', 'vehicle_company', 'year'], name='vehicle_inf_id_5338a4_idx'),
        ),
    ]
