# Generated by Django 3.1.7 on 2021-04-03 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210404_0227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_by', to='api.user')),
                ('review_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_for', to='api.user')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['id', 'review_by', 'review_for', 'review', 'rating'], name='review_id_abbec0_idx'),
        ),
    ]
