# Generated by Django 3.1.7 on 2021-04-05 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210404_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('user_lat', models.CharField(blank=True, max_length=250, null=True)),
                ('user_lng', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('cancelled_vendors', models.CharField(blank=True, max_length=250, null=True)),
                ('request_status', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_ids', to='api.service')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userids', to='api.user')),
                ('vendor_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_ids', to='api.user')),
            ],
            options={
                'db_table': 'service_request',
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['id', 'service_id', 'user_id', 'vendor_id', 'service_note', 'address'], name='service_req_id_7ebcc8_idx'),
        ),
    ]
