# Generated by Django 3.1.7 on 2021-04-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210405_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='services_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_ids', to='api.service'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='request_status',
            field=models.BooleanField(default=False),
        ),
    ]
