# Generated by Django 3.1.7 on 2021-04-16 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_device_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True)),
                ('service_note', models.TextField(blank=True, max_length=1000, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, max_length=250, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'booking_history',
            },
        ),
        migrations.RemoveIndex(
            model_name='vehiclecolor',
            name='vehicle_col_id_aefffd_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicleinfo',
            name='vehicle_inf_id_5338a4_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehiclemodel',
            name='vehicle_mod_id_2af592_idx',
        ),
        migrations.RemoveField(
            model_name='vehiclecolor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='vehicle_company',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='vehicle_model',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='vehicle_color',
        ),
        migrations.RemoveField(
            model_name='vehiclemodel',
            name='years',
        ),
        migrations.AddField(
            model_name='service',
            name='extra_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclecolor',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model', to='api.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='vehicleinfo',
            name='color_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='color_id', to='api.vehiclecolor'),
        ),
        migrations.AddIndex(
            model_name='vehiclecolor',
            index=models.Index(fields=['id', 'model', 'color'], name='vehicle_col_id_c1cc59_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinfo',
            index=models.Index(fields=['id', 'color_id', 'year'], name='vehicle_inf_id_738616_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiclemodel',
            index=models.Index(fields=['id', 'vehicle_company', 'name'], name='vehicle_mod_id_7451e0_idx'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='serviceids', to='api.service'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='api.vehicleinfo'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicemen', to='api.user'),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['id', 'vehicle', 'vendor', 'service', 'rating', 'mobile', 'latitude', 'longitude', 'payment_status', 'price', 'name'], name='booking_his_id_2de264_idx'),
        ),
    ]
