# Generated by Django 3.1.7 on 2021-04-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_vehiclecolor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='card_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
