# Generated by Django 3.1.7 on 2021-04-17 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_bookinghistory_card_token'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='service_req_id_7ebcc8_idx',
        ),
        migrations.RenameField(
            model_name='servicerequest',
            old_name='address',
            new_name='review',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='cancelled_vendors',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='request_time',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_note',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user_lat',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='user_lng',
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='request_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_ids', to='api.bookinghistory'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='services_id',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['id', 'request_id', 'vendor_id', 'request_status', 'service_status'], name='service_req_id_7308e0_idx'),
        ),
    ]
