# Generated by Django 3.1.7 on 2021-04-18 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210418_0019'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about_us', models.TextField(blank=True, max_length=1000, null=True)),
                ('help', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'App detail',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, help_text='discount in percentage', null=True)),
                ('detail', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'offer',
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['id', 'name', 'promo_code', 'discount', 'detail'], name='offer_id_40efaa_idx'),
        ),
        migrations.AddIndex(
            model_name='appdetail',
            index=models.Index(fields=['id', 'about_us', 'help'], name='App detail_id_6e721d_idx'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='api.offer'),
        ),
    ]
