# Generated by Django 3.1.7 on 2021-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210419_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='help_number',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='office_number',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
