# Generated by Django 3.1.7 on 2021-04-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210419_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='about_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appdetail',
            name='help_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='help_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appdetail',
            name='office_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
