# Generated by Django 3.1.7 on 2021-04-22 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210421_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
