# Generated by Django 3.1.7 on 2021-05-08 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_bookinghistory_cancelled_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='QNaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_service', to='api.service')),
            ],
            options={
                'db_table': 'qna',
            },
        ),
        migrations.AddField(
            model_name='appdetail',
            name='booking_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='QnaOptionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.CharField(blank=True, max_length=250, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('qna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qna_id', to='api.qnamodel')),
            ],
            options={
                'db_table': 'qna_option',
            },
        ),
        migrations.AddIndex(
            model_name='qnaoptionmodel',
            index=models.Index(fields=['id', 'qna', 'option'], name='qna_option_id_fb932a_idx'),
        ),
        migrations.AddIndex(
            model_name='qnamodel',
            index=models.Index(fields=['id', 'service', 'name'], name='qna_id_37596d_idx'),
        ),
    ]
