# Generated by Django 3.1.7 on 2021-05-16 15:26

import api.utils.common
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210508_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(blank=True, max_length=250, null=True)),
                ('account_number', models.CharField(blank=True, max_length=250, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=250, null=True)),
                ('personal_id', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.BooleanField(default=False)),
                ('front_image', models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename)),
                ('back_image', models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='api.user')),
            ],
            options={
                'db_table': 'payment_account',
            },
        ),
        migrations.AddIndex(
            model_name='paymentaccount',
            index=models.Index(fields=['id', 'user', 'account_name', 'account_number', 'routing_number', 'personal_id', 'address', 'zip_code'], name='payment_acc_id_07248b_idx'),
        ),
    ]
