# Generated by Django 3.1.7 on 2021-05-17 15:28

import api.utils.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20210516_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='appdetail',
            name='terms',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentaccount',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
    ]
