# Generated by Django 3.1.7 on 2021-05-20 04:57

from django.db import migrations
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210517_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinghistory',
            name='signature',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
    ]
