# Generated by Django 3.1.7 on 2021-05-21 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_bookinghistory_signature'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='vehiclecolor',
            name='vehicle_col_id_c1cc59_idx',
        ),
        migrations.RemoveIndex(
            model_name='vehicleinfo',
            name='vehicle_inf_id_738616_idx',
        ),
        migrations.RemoveField(
            model_name='vehiclecolor',
            name='model',
        ),
        migrations.RemoveField(
            model_name='vehicleinfo',
            name='color_id',
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='vehicle_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_color', to='api.vehiclecolor'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='vehicle_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_year', to='api.vehicleinfo'),
        ),
        migrations.AlterField(
            model_name='bookinghistory',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='api.vehiclemodel'),
        ),
        migrations.AddIndex(
            model_name='vehiclecolor',
            index=models.Index(fields=['id', 'name', 'color'], name='vehicle_col_id_aefffd_idx'),
        ),
        migrations.AddIndex(
            model_name='vehicleinfo',
            index=models.Index(fields=['id', 'year'], name='vehicle_inf_id_7d4160_idx'),
        ),
    ]
