# Generated by Django 3.1.7 on 2021-05-22 16:40

from django.db import migrations, models
import django_base64field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20210522_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='deleted_at',
            new_name='arrived',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='signature',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='terms',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='eta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='signature',
            field=django_base64field.fields.Base64Field(blank=True, default='', max_length=900000, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='terms',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='email',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
