# Generated by Django 3.1.7 on 2021-05-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210522_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='arrived',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='completed',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='eta',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
