# Generated by Django 3.1.7 on 2021-05-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20210523_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='image1',
            field=models.TextField(blank=True, max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='image2',
            field=models.TextField(blank=True, max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='image3',
            field=models.TextField(blank=True, max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='image4',
            field=models.TextField(blank=True, max_length=900000, null=True),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='signature',
            field=models.TextField(blank=True, max_length=900000, null=True),
        ),
    ]
