# Generated by Django 3.1.7 on 2021-05-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210531_0048'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookinghistory',
            name='booking_his_id_f6bc96_idx',
        ),
        migrations.RemoveField(
            model_name='bookinghistory',
            name='device_token',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='device_token',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['id', 'vehicle', 'vendor', 'service', 'rating', 'mobile', 'latitude', 'longitude', 'payment_status', 'price', 'name'], name='booking_his_id_2de264_idx'),
        ),
    ]
