# Generated by Django 3.1.7 on 2021-06-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_auto_20210531_0053'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='auth_user_id_afe805_idx',
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id', 'first_name', 'last_name', 'email', 'is_active', 'latitude', 'longitude', 'services_id'], name='auth_user_id_28769b_idx'),
        ),
    ]
