# Generated by Django 3.1.7 on 2021-06-28 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210613_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageDelivery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('delivery_from', models.CharField(blank=True, max_length=250, null=True)),
                ('delivery_to', models.CharField(blank=True, max_length=250, null=True)),
                ('details', models.TextField(blank=True, max_length=1000, null=True)),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_request_id', to='api.bookinghistory')),
            ],
            options={
                'db_table': 'package_delivery',
            },
        ),
        migrations.AddIndex(
            model_name='packagedelivery',
            index=models.Index(fields=['id', 'request_id', 'delivery_from', 'delivery_to', 'details'], name='package_del_id_372dda_idx'),
        ),
    ]
