# Generated by Django 3.1.7 on 2021-07-21 09:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20210628_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenderDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('w9_form', models.TextField(blank=True, max_length=1000, null=True)),
                ('driver_licence_front', models.TextField(blank=True, max_length=1000, null=True)),
                ('driver_licence_back', models.TextField(blank=True, max_length=1000, null=True)),
                ('reg_insurence', models.TextField(blank=True, max_length=1000, null=True)),
                ('background_check', models.TextField(blank=True, max_length=1000, null=True)),
                ('authorization_form', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to='api.user')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
        migrations.AddIndex(
            model_name='venderdetails',
            index=models.Index(fields=['id', 'user', 'w9_form', 'driver_licence_front', 'driver_licence_back', 'reg_insurence', 'background_check', 'authorization_form'], name='user_detail_id_994c5b_idx'),
        ),
    ]
