# Generated by Django 3.1.7 on 2021-07-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210721_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venderdetails',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to='api.user'),
        ),
    ]
