# Generated by Django 3.1.7 on 2021-07-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20210721_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venderdetails',
            name='authorization_form',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='background_check',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='driver_licence_back',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='driver_licence_front',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='reg_insurence',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_details', to='api.user'),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='w9_form',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
