# Generated by Django 3.1.7 on 2021-07-22 07:57

import api.utils.common
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20210722_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venderdetails',
            name='authorization_form',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='background_check',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='driver_licence_back',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='driver_licence_front',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='reg_insurence',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
        migrations.AlterField(
            model_name='venderdetails',
            name='w9_form',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.common.path_and_rename),
        ),
    ]
