# Generated by Django 3.1.7 on 2021-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_auto_20210722_1327'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='verificationcode',
            name='verificatio_id_1ec3da_idx',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddIndex(
            model_name='verificationcode',
            index=models.Index(fields=['id', 'user', 'mobile', 'code', 'first_name', 'last_name', 'email'], name='verificatio_id_dc33e8_idx'),
        ),
    ]
