# Generated by Django 3.1.7 on 2021-09-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_user_doc_verify'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='venderdetails',
            name='user_detail_id_994c5b_idx',
        ),
        migrations.RenameField(
            model_name='venderdetails',
            old_name='driver_licence_back',
            new_name='ica_form',
        ),
        migrations.AddIndex(
            model_name='venderdetails',
            index=models.Index(fields=['id', 'user', 'w9_form', 'driver_licence_front', 'ica_form', 'reg_insurence', 'background_check', 'authorization_form'], name='user_detail_id_d68048_idx'),
        ),
    ]
