# Generated by Django 3.1.7 on 2021-09-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20210917_0115'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='bookinghistory',
            name='booking_his_id_2de264_idx',
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='tip',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='bookinghistory',
            index=models.Index(fields=['id', 'vehicle', 'vendor', 'service', 'rating', 'mobile', 'latitude', 'longitude', 'payment_status', 'price', 'name', 'tip'], name='booking_his_id_0e7b9c_idx'),
        ),
    ]
