# Generated by Django 3.1.7 on 2021-09-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210917_2335'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='servicerequest',
            name='service_req_id_7308e0_idx',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='step',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['id', 'request_id', 'vendor_id', 'request_status', 'service_status', 'step'], name='service_req_id_5145ea_idx'),
        ),
    ]
