# Generated by Django 3.1.7 on 2021-09-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_auto_20210923_0317'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=50, null=True)),
                ('answer', models.TextField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'faq',
            },
        ),
        migrations.AddIndex(
            model_name='faq',
            index=models.Index(fields=['id', 'question', 'answer'], name='faq_id_d8ea90_idx'),
        ),
    ]
